---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Mise"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0" # once a week

jobs:
  mise:
    name: upgrade-tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/tilde/private_dot_config/mise/config.toml"
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upgrade dependencies
        run: mise upgrade --bump

      - name: Check if .mise.toml changed
        id: changes
        run: |
          git diff --quiet "$MISE_GLOBAL_CONFIG_FILE" || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Generate PR Body
        if: ${{ steps.changes.outputs.changed == 'true' }}
        id: prdiff
        run: |
          {
            echo 'body<<EOF'
            echo 'Upgraded dependencies found in `.mise.toml`:'
            echo
            echo '```diff'
            git diff "$MISE_GLOBAL_CONFIG_FILE"
            echo '```'
            echo
            echo '> [!TIP]'
            echo '> Merge this pull request and then run `mise upgrade --bump` on your workstation.'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          branch: "mise-upgrade/${{ github.run_id }}"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            "${{ steps.prdiff.outputs.body }}"
            ```
