---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Mise"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0" # once a week

jobs:
  mise:
    name: upgrade-tools
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      MISE_GLOBAL_CONFIG_FILE: "${{ github.workspace }}/tilde/private_dot_config/mise/config.toml"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upgrade dependencies
        run: mise upgrade --bump

      - name: Check if .mise.toml changed
        id: changes
        run: |
          git diff --quiet "$MISE_GLOBAL_CONFIG_FILE" || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Generate PR Body
        if: ${{ steps.changes.outputs.changed == 'true' }}
        id: prdiff
        run: |
          {
            echo 'body<<EOF'
            echo 'Upgraded dependencies found in `.mise.toml`:'
            echo
            echo '```diff'
            git diff "$MISE_GLOBAL_CONFIG_FILE"
            echo '```'
            echo
            echo '> [!TIP]'
            echo '> Merge this pull request and then run `mise upgrade --bump` on your workstation.'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: ${{ steps.changes.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          title: "chore(mise): upgrade dependencies"
          commit-message: "chore(mise): upgrade dependencies"
          branch: "mise-upgrade/${{ github.run_id }}"
          body: |
            Upgraded dependencies found in `.mise.toml`:

            ```diff
            "${{ steps.prdiff.outputs.body }}"
            ```
